import Navbar from "@/components/shared/Navbar";
import { Toaster } from "@/components/ui/sonner";
import { Providers } from "@/redux/provider";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <div className="flex flex-col h-screen">
            <Navbar />
            <div className="flex flex-1">
              <div className="min-w-[200px] max-w-[200px] py-3 px-5 border-r border-gray-300">
                <span className="bg-indigo-600 w-full block text-white py-1 px-2 rounded-sm">
                  Dashboard
                </span>
              </div>
              <div className="flex-1 space-y-3 py-3 px-5">{children}</div>
            </div>
          </div>
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
